const path = {
  home: '/',
  user: '/user',
  blog: '/blog',
  blogDetail: '/blog/:blogDetail',
  profile: '/user/profile',
  changePassword: '/user/password',
  historyPurchase: '/user/purchase',
  login: '/login',
  register: '/register',
  verifyEmail: '/verifyEmail',
  logout: '/logout',
  products: '/products',
  gt: '/gioi-thieu',
  cs1: '/chinh-sach-bao-hanh',
  cs2: '/chinh-sach-bao-mat-thong-tin',
  cs3: '/chinh-sach-doi-tra-hoan-tien',
  productDetail: ':nameId',
  cart: '/cart',
  checkout: '/checkout',
  payDone: '/returnpay',
  orderDetail: '/user/order-detail',
  forgotPassWord: '/forgot-password',
  resetPassword: '/reset-password/:tokenPassword'
} as const
export default path
